select * from emp;
select * from dept;
select * from salgrade;
select empno,ename,job,sal from emp;
select ename,sal,sal*12 as "annual sal" from emp;
select ename ||' working as '||job from emp;
select ename||' joined on '||hiredate from emp;
select ename||' Earns '||sal*12||' per year.' from emp;
select interval '300' month,
        interval '54-2' year to month,
        interval '11:12:10.1234567' hours to second from dual;
select ename, sal as basic,comm as bonus from emp;
select *from emp where empno=7844;
select * from emp where job='CLERK';
select count(job) from emp where job='CLERK';
select * from emp where deptno=10 and job='CLERK';
select * from emp where deptno=10;
select * from emp where job='CLERK' OR job='MANAGER';
select * from emp where job='CLERK' or job='MANAGER';
select * from emp where deptno=10 AND job='CLERK';
select * from emp where deptno=10 AND job='MANAGER';
select *from emp where deptno=10;
select *from emp where deptno=10 and job='CLERK';
select * from emp where sal between 2000 and 5000;
select * from emp where sal>=2000 and sal<=5000;
select * from emp where hiredate >'31-JAN-81';
select * from emp where job='CLERK' or job='MANAGER' AND sal>2000;
select * from emp where comm is  not null;
select * from emp where hiredate between'01-JAN-1981' and '31-DEC-1981';
select * from emp where job in ('CLERK','MANAGER');
select * from emp where deptno in(10,20,30);
select * from emp where deptno not in(10,20);
select * from emp where ename like'S%';
select * from emp where ename like'%S';
select * from emp where ename not like'%S%';
select * from emp where ename like'_A%';
select * from emp where hiredate like'%JAN%';
select * from emp where hiredate like'%81%';
select * from emp where hiredate like'0%';
select * from emp where sal like'_____';
select * from emp where job in('CLERK','%MAN%');
select * from emp order by sal;
select * from emp order by sal desc ;
select * from emp where deptno=10 order by sal;
select * from emp order by deptno,sal desc;
select * from emp order by comm nulls last;
select * from emp order by comm desc nulls first;
select distinct job from emp;
select distinct deptno,job from emp order by deptno;
select lower(ename) from emp;
select initcap(ename) from emp;
update emp set ename=lower(ename);
select * from emp;
COMMIT WORK;
update emp set ename=initcap(ename);
select * from emp;
update emp set ename=upper(ename);
select * from emp;
select length('zameer') from dual;
select ename from emp where length(ename)=5;
select substr('hello',2,4)from dual;
select substr('hello world',-5,4)from dual;
select ename from emp where substr(ename,1,1)='S';
select instr('hello wellcome','o') from dual;
select instr('hello wellcome','o',1,2) from dual;
select instr('hello wellcome','l') from dual;
select instr('hello wellcome','l',1,4) from dual;
select * from emp where instr(ename,'S')<>0;
select substr('zammi@gmail.com',1,instr('zammi@gmail.com','@')-1) from dual;
